import { Course } from "@prisma/client";

const recipes = [
  {
    title: "Chocolate Cake",
    course: Course.DESSERT,
    cuisine: "American",
    ingredients: [
      {
        name: "all-purpose flour",
        amount: 2,
        unitType: "cups",
        unit: "",
      },
      {
        name: "granulated sugar",
        amount: 2,
        unitType: "cups",
        unit: "",
      },
      {
        name: "cocoa powder",
        amount: 0.75,
        unitType: "cup",
        unit: "",
      },
      {
        name: "baking powder",
        amount: 2,
        unitType: "teaspoons",
        unit: "",
      },
      {
        name: "baking soda",
        amount: 1,
        unitType: "teaspoon",
        unit: "",
      },
      {
        name: "salt",
        amount: 1,
        unitType: "teaspoon",
        unit: "",
      },
      {
        name: "buttermilk",
        amount: 1,
        unitType: "cup",
        unit: "",
      },
      {
        name: "vegetable oil",
        amount: 0.5,
        unitType: "cup",
        unit: "",
      },
      {
        name: "eggs",
        amount: 2,
        unitType: "",
        unit: "",
      },
      {
        name: "vanilla extract",
        amount: 2,
        unitType: "teaspoons",
        unit: "",
      },
      {
        name: "boiling water",
        amount: 1,
        unitType: "cup",
        unit: "",
      },
    ],
    steps: [
      "Preheat oven to 350°F.",
      "Grease and flour two 9-inch round baking pans.",
      "In a large mixing bowl, combine flour, sugar, cocoa powder, baking powder, baking soda, and salt.",
      "Add buttermilk, vegetable oil, eggs, and vanilla extract, and mix until combined.",
      "Stir in boiling water. Batter will be thin, but that's okay!",
      "Pour batter evenly into prepared pans.",
      "Bake for 30-35 minutes, or until a toothpick inserted in the center comes out clean.",
      "Remove from oven and let cool for 10 minutes.",
      "Remove cakes from pans and transfer to a wire rack to cool completely.",
      "Frost with your favorite frosting and enjoy!",
    ],
  },

  {
    title: "Pho",
    course: Course.DINNER,
    cuisine: "Vietnamese",
    ingredients: [
      {
        name: "beef bones",
        amount: 1.5,
        unitType: "pounds",
        unit: "lbs",
      },
      { name: "onion", amount: 1, unitType: "large", unit: "" },
      { name: "ginger", amount: 3, unitType: "inches", unit: "" },
      { name: "star anise", amount: 2, unitType: "pieces", unit: "" },
      {
        name: "cinnamon stick",
        amount: 1,
        unitType: "stick",
        unit: "",
      },
      {
        name: "fennel seeds",
        amount: 1,
        unitType: "teaspoon",
        unit: "tsp",
      },
      {
        name: "coriander seeds",
        amount: 1,
        unitType: "teaspoon",
        unit: "tsp",
      },
      { name: "cardamom pods", amount: 3, unitType: "pods", unit: "" },
      { name: "salt", amount: 1, unitType: "teaspoon", unit: "tsp" },
      {
        name: "rice noodles",
        amount: 1,
        unitType: "package",
        unit: "",
      },
      {
        name: "sirloin steak",
        amount: 0.5,
        unitType: "pounds",
        unit: "lbs",
      },
      { name: "green onions", amount: 2, unitType: "stalks", unit: "" },
      { name: "cilantro", amount: 0.5, unitType: "cup", unit: "cups" },
      { name: "lime", amount: 1, unitType: "wedge", unit: "" },
    ],
    steps: [
      "Preheat oven to 425°F. Roast beef bones for 30 minutes.",
      "Chop onion and ginger in half. Add to a pot with 6 quarts of water.",
      "Add the roasted beef bones to the pot.",
      "Add star anise, cinnamon stick, fennel seeds, coriander seeds, cardamom pods, and salt to the pot.",
      "Simmer on low heat for at least 3 hours. Skim off any impurities that rise to the surface.",
      "Strain the broth and discard the solids. Keep the broth warm.",
      "Cook rice noodles according to package instructions. Drain and rinse with cold water.",
      "Slice the sirloin steak as thinly as possible. Chop green onions and cilantro.",
      "Divide the noodles between bowls. Top with sliced steak, green onions, and cilantro.",
      "Pour the hot broth over the noodles and steak.",
      "Squeeze a wedge of lime into each bowl and serve.",
    ],
  },
  {
    title: "Egg and Cheese Breakfast Sandwich",
    course: Course.BREAKFAST,
    cuisine: "American",
    ingredients: [
      {
        name: "English muffin",
        amount: 1,
        unitType: "piece",
        unit: "",
      },
      { name: "Egg", amount: 2, unitType: "piece", unit: "" },
      {
        name: "Cheddar cheese",
        amount: 1,
        unitType: "slice",
        unit: "",
      },
      { name: "Butter", amount: 1, unitType: "tablespoon", unit: "" },
      { name: "Salt", amount: 1, unitType: "pinch", unit: "" },
      { name: "Black pepper", amount: 1, unitType: "pinch", unit: "" },
    ],
    steps: [
      "Toast the English muffin halves.",
      "In a small bowl, whisk together the eggs, salt, and pepper.",
      "Melt the butter in a nonstick skillet over medium heat.",
      "Add the egg mixture to the skillet and cook, stirring occasionally, until the eggs are scrambled and set, about 2-3 minutes.",
      "Place the cheese slice on one half of the toasted English muffin.",
      "Top the cheese with the scrambled eggs and then with the other half of the English muffin.",
      "Serve hot.",
    ],
  },
  {
    title: "Cola-Braised Beef with Risotto",
    course: Course.DINNER,
    cuisine: "Italian",
    ingredients: [
      { name: "Beef chuck roast", amount: 2.5, unitType: "pounds", unit: "" },
      { name: "Salt", amount: 2, unitType: "teaspoons", unit: "" },
      { name: "Black pepper", amount: 1, unitType: "teaspoon", unit: "" },
      { name: "Olive oil", amount: 2, unitType: "tablespoons", unit: "" },
      { name: "Onion", amount: 1, unitType: "large", unit: "diced" },
      { name: "Garlic", amount: 4, unitType: "cloves", unit: "minced" },
      { name: "Cola", amount: 1.5, unitType: "cups", unit: "" },
      { name: "Beef broth", amount: 1.5, unitType: "cups", unit: "" },
      { name: "Arborio rice", amount: 1, unitType: "cup", unit: "" },
      { name: "Parmesan cheese", amount: 1, unitType: "cup", unit: "grated" },
      { name: "Butter", amount: 2, unitType: "tablespoons", unit: "" },
      {
        name: "Fresh parsley",
        amount: 2,
        unitType: "tablespoons",
        unit: "chopped",
      },
    ],
    steps: [
      "Preheat the oven to 325°F.",
      "Season the beef with salt and black pepper.",
      "Heat the olive oil in a large Dutch oven or oven-safe pot over medium-high heat.",
      "Add the beef to the pot and brown on all sides, about 8 minutes total.",
      "Remove the beef from the pot and set aside.",
      "Add the diced onion and minced garlic to the pot and sauté until softened, about 5 minutes.",
      "Add the cola and beef broth to the pot and stir to combine.",
      "Return the beef to the pot and bring to a simmer.",
      "Cover the pot and transfer to the oven.",
      "Braise the beef in the oven for 2-2.5 hours, or until tender.",
      "While the beef is cooking, prepare the risotto according to package instructions, using the Arborio rice, Parmesan cheese, and butter.",
      "Once the beef is tender, remove the pot from the oven and transfer the beef to a serving platter.",
      "Use a slotted spoon to remove the onion and garlic from the pot and discard.",
      "Place the pot on the stove over medium-high heat and bring the remaining liquid to a boil.",
      "Reduce the heat to medium and simmer until the liquid has thickened, about 10 minutes.",
      "To serve, spoon the risotto onto individual plates and top with slices of the braised beef.",
      "Drizzle the reduced liquid from the pot over the beef and sprinkle with chopped fresh parsley.",
      "Serve hot.",
    ],
  },
  {
    title: "Chicken Tikka Masala",
    course: Course.DINNER,
    cuisine: "Indian",
    ingredients: [
      {
        name: "boneless, skinless chicken breasts",
        amount: 1,
        unitType: "pound",
        unit: "lb",
      },
      {
        name: "yogurt",
        amount: 1,
        unitType: "cup",
        unit: "cup",
      },
      {
        name: "lemon juice",
        amount: 2,
        unitType: "tablespoon",
        unit: "tbsp",
      },
      {
        name: "ginger",
        amount: 2,
        unitType: "teaspoon",
        unit: "tsp",
      },
      {
        name: "garlic",
        amount: 2,
        unitType: "teaspoon",
        unit: "tsp",
      },
      {
        name: "garam masala",
        amount: 2,
        unitType: "teaspoon",
        unit: "tsp",
      },
      {
        name: "paprika",
        amount: 2,
        unitType: "teaspoon",
        unit: "tsp",
      },
      {
        name: "salt",
        amount: 1,
        unitType: "teaspoon",
        unit: "tsp",
      },
      {
        name: "butter",
        amount: 2,
        unitType: "tablespoon",
        unit: "tbsp",
      },
      {
        name: "onion",
        amount: 1,
        unitType: "large",
        unit: "",
      },
      {
        name: "tomatoes",
        amount: 2,
        unitType: "large",
        unit: "",
      },
      {
        name: "heavy cream",
        amount: 1,
        unitType: "cup",
        unit: "cup",
      },
      {
        name: "cilantro",
        amount: 2,
        unitType: "tablespoon",
        unit: "tbsp",
      },
      {
        name: "cooked basmati rice",
        amount: 2,
        unitType: "cup",
        unit: "cups",
      },
    ],
    steps: [
      "Cut the chicken into bite-sized pieces.",
      "Mix together the yogurt, lemon juice, ginger, garlic, garam masala, paprika, and salt. Add the chicken and marinate for at least an hour, or overnight.",
      "Melt the butter in a large skillet over medium heat. Add the onion and sauté until translucent.",
    ],
  },
];

export { recipes };
